spring:
  profiles:
    active: local
  jwt:
    secret-key: '!mangomango@'
    valid-millisecond: 1800000

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    root: info
    org:
      hibernate:
        type: trace